### ISSUE TITLE
Plugin doesn't like running under Java 9

### ISSUE THREAD

**Issue by dnault** [couchbaselabs/couchbase-elasticsearch-connector#191]
because javax.xml.bind.DatatypeConverter is no longer on the class path by default.

```
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
  at org.elasticsearch.transport.couchbase.capi.ElasticSearchCAPIBehavior.bulkDocs(ElasticSearchCAPIBehavior.java:360) ~[elasticsearch-transport-couchbase-3.0.1-cypress-es5.6.7-all.jar:?]
  at com.couchbase.capi.servlet.CAPIServlet.handleBulkDocs(CAPIServlet.java:532) ~[couchbase-capi-server-1.6.3.jar:?]
  at com.couchbase.capi.servlet.CAPIServlet.service(CAPIServlet.java:89) ~[couchbase-capi-server-1.6.3.jar:?]
```

This class is only used for Base64 decoding. The plugin should depend on some other Base64 implementation that's guaranteed to be present.

**Comment by dnault** [comment]
https://issues.couchbase.com/browse/CBES-82
